check-for-update: true
notify-console: true
notify-admin: true
permission: "clientdetector.admin"

messages:
  #GUI
  gui-main-title: "<#888888>▶ Clients (Page %page%)"
  gui-sub-title: "<#888888>▶ %brand% (Page %page%)"
  gui-next-page: "<#ffa500>« Page Précédente"
  gui-previous-page: "<#ffa500>Page Suivante »"
  gui-back-button: "<#ff5555>Retour au Menu Principal"
  gui-action-title: "<#888888>Actions: <#55ffff>%player%"
  gui-action-teleport: "<#55ff55>➤ Se téléporter"
  gui-client-lore:
    - "<#aaaaaa>Cliquez pour voir les joueurs."
    - ""
    - "<#ffffff>Joueurs : <#55ffff>%count%"
  gui-player-lore:
    - "<#aaaaaa>UUID: <#ffffff>%uuid%"
    - "<#aaaaaa>Bedrock: <#55ffff>%is_bedrock%"

  prefix: "<#888888>[<gradient:#55ffff:#5555ff>ClientDetector</gradient><#888888>] <#ffffff>"
  reload: "<#55ff55>La configuration a été rechargée !"
  no-permission: "<#ff5555>Tu n'as pas la permission d'utiliser cela."
  player-info: "<#aaaaaa>Joueur: <#55ffff>%player% <#888888>| <#aaaaaa>Client: <#55ffff>%brand% <#888888>| <#aaaaaa>Bedrock: <#55ffff>%is_bedrock%"
  player-check: "<#aaaaaa>Infos sur <#55ffff>%target% <#888888>: <#aaaaaa>Client: <#55ffff>%brand% <#888888>| <#aaaaaa>Bedrock: <#55ffff>%is_bedrock%"
  player-not-found: "<#ff5555>Ce joueur n'est pas en ligne."


webhooks:
  enabled: true
  url: "https://discord.com/api/webhooks/..."
  alert-bedrock: true # Si true, ignore la liste et alerte pour tout le monde
  all-clients: true
  alert-brands:
    - "forge"
    - "fabric"
  message: "🔔 **%player%** a rejoint avec **%brand%** (Bedrock: %is_bedrock%)"